### ISSUE TITLE
Deny Access to Door

### ISSUE THREAD

**Issue by agable74** [paulr4321/keyCard#2]
Narrative #1:
In order to get to my office
As an employee
I want to be able to swipe my key card and enter.

Scenario #1: User has permission
Given user has access to door
When user swipes key card on door
Then door opens and panel blinks green

**Comment by agable74** [comment]
Can you move to top priority pls

**Comment by pkshort** [comment]
Employee Fields:
ID, Name, Permissions

**Comment by pkshort** [comment]
Door Object:
ID
