### ISSUE TITLE
Grant Access to Door

### ISSUE THREAD

**Issue by agable74** [paulr4321/keyCard#3]
Narrative #1: 
In order to get to my office
As an employee
I want to be able to swipe my key card and enter.

Scenario #2: User does not have permission
Given user does not have access to door
When user swipes key card on door
Then door does not open and panel blinks red

**Comment by agable74** [comment]
Can you move to second priority pls

**Comment by pkshort** [comment]
Employee Fields: 
ID, Name, Permissions

**Comment by pkshort** [comment]
Door Object:
ID

**Comment by bklopcic** [comment]
Door has list of users. Make users in the list can be granted access (via a print statement)
