### ISSUE TITLE
Manage Permissions

### ISSUE THREAD

**Issue by agable74** [paulr4321/keyCard#4]
Narrative #4:
In order to manage permissions
As an administrator
I want to select users and add, remove, and modify permissions.

Scenario #1: Add permissions
Given the security rep has accepted a user application
When I receive information about a card and door
Then I can add the permission to the card

**Comment by bklopcic** [comment]
Manager can see a list of all permissions requests that have been cleared by the security rep. The manager can choose a request and add that user to the system.

**Comment by agable74** [comment]
Done when manager/administrator can add and remove permissions for a user
