### ISSUE TITLE
Implement Menu State

### ISSUE THREAD

**Issue by bklopcic** [paulr4321/keyCard#45]

**Comment by noclipdelux** [comment]
Time spent: ~1hr

**Comment by noclipdelux** [comment]
Still need to implement quit option

**Comment by noclipdelux** [comment]
Time spent: ~2hr

**Comment by noclipdelux** [comment]
We need to fix how these states are initialized. Instead of initializing with a current state, we should ini them as default and direct the control flow from there.

**Comment by noclipdelux** [comment]
Change exit application to a new ENUM so driver can take control
