### ISSUE TITLE
Implement Application View

### ISSUE THREAD

**Issue by bklopcic** [paulr4321/keyCard#52]
View list of all doors
request access to specific door
request is saved in persistent data storage

**Comment by noclipdelux** [comment]
Time spent: ~1

**Comment by noclipdelux** [comment]
Still need to implement DAO object so we can write the applications in. In addition, the consol function that takes user input has an extra scanner.nextLine() call that causes a lot of formatting problems.

**Comment by noclipdelux** [comment]
Edit application submit function to use request and fix constructor

**Comment by bklopcic** [comment]
Updated a few things for validation and overall consistency. 30 mins
