### ISSUE TITLE
Record Class

### ISSUE THREAD

**Issue by phernandoe** [paulr4321/keyCard#77]

**Comment by phernandoe** [comment]
Has userID, doorID, time, outcome(either granted or denied)

**Comment by noclipdelux** [comment]
Timestamp will be created when user swipes in. In the record class, the timestamp function will be called when the outcome is calculated.

**Comment by noclipdelux** [comment]
Took about 2 hours with planning/discussion and implementation.

**Comment by noclipdelux** [comment]
Adding ~1 more hour
